# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: |
    sudo apt-get install python3-pip
    sudo apt-get install python3-setuptools
    pip3 install virtualenv
    sudo apt-get install python-virtualenv
    pip3 install -r requirements.txt
    virtualenv venv
    source venv/bin/activate
    pip3 install django
    django-admin --version
    pip3 install pytest
    pip3 install pytest-cov
    python3 -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    python3 --version
    python --version
  displayName: 'Install tools'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
