# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install python3-pip
    sudo apt-get install python3-setuptools
    pip3 install virtualenv
  displayName: 'Install tools'

- script: pip3 install -r requirements.txt
  displayName: 'Install requirements'

- script: virtualenv venv
  displayName: 'Creating virtual environment'

- script: source venv/bin/activate
  displayName: 'Starting virtual environment'
  
- script: python manage.py test

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
