# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install python3-pip
    sudo apt-get install python3-setuptools
    pip3 install virtualenv
    sudo apt-get install python-virtualenv
    pip3 install -r requirements.txt
    virtualenv venv
    source venv/bin/activate
    pip install django==2.2
    django-admin --version
    python -m pip install flake8
    flake8 .
  displayName: 'Install tools'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
